/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;
import Controladores.ControladorHabitacion;
import Modelo.Habitaciones;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author apnil
 */
public class JDialogAsignarHabitacion extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogAsignarHabitacion.class.getName());

    /**
     * Creates new form JDialogAsignarHabitacion
     */
    private int idAsigancion;
    
    public JDialogAsignarHabitacion(java.awt.Frame parent, boolean modal)throws Exception {
        super(parent, modal);
        initComponents();
        eventoTabla();
        CargarHabitacionesDiponibles();
    }
    
    private void CargarHabitacionesDiponibles() throws Exception{
        DefaultTableModel modelo = (DefaultTableModel)tablahabitaciones.getModel();
        modelo.setRowCount(0); 
        ControladorHabitacion CH = new ControladorHabitacion();
        try{
            ArrayList<Habitaciones> list = CH.HabitacionesDisponibles();
            for (Habitaciones h : list){
                modelo.addRow(new Object[]{
                    h.getHabitacionID(),
                    h.getNombre(),
                    h.getPiso(),
                    h.getTipo(),
                   (h.getEstado() == 0 ? "Disponible" : "Ocupado"),
                    " "
                });
            }
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar habitaciones: "+ex.getMessage());
        }
    }
    private void eventoTabla(){
        tablahabitaciones.getColumnModel().getColumn(5).setCellRenderer(new TableActionCellRender("Asignar"));
        TableActionEvent event = new TableActionEvent() {
            @Override
            public void Action(int row, String texto) {
                idAsigancion = Integer.parseInt(tablahabitaciones.getValueAt(row, 0).toString());
                JOptionPane.showMessageDialog(rootPane, "Se asigno la emergencia y paciente a la habitacion seleccionada", "Exito", JOptionPane.INFORMATION_MESSAGE);
                dispose();
            }
        };
        tablahabitaciones.getColumnModel().getColumn(5).setCellEditor(new TableActionCellEditor(event, "Asignar"));
        
        DefaultTableCellRenderer centrado = new DefaultTableCellRenderer();
        centrado.setHorizontalAlignment(SwingConstants.CENTER);
        tablahabitaciones.getColumnModel().getColumn(0).setCellRenderer(centrado);
        tablahabitaciones.getColumnModel().getColumn(1).setCellRenderer(centrado);
        tablahabitaciones.getColumnModel().getColumn(2).setCellRenderer(centrado);
        tablahabitaciones.getColumnModel().getColumn(3).setCellRenderer(centrado);
        tablahabitaciones.getColumnModel().getColumn(4).setCellRenderer(centrado);
        
    }
     public int getIdHabitacionSeleccionada() {
        return idAsigancion;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablahabitaciones = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(976, 627));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        tablahabitaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Piso", "Tipo", "Estado", "Asignar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablahabitaciones);
        if (tablahabitaciones.getColumnModel().getColumnCount() > 0) {
            tablahabitaciones.getColumnModel().getColumn(0).setResizable(false);
            tablahabitaciones.getColumnModel().getColumn(1).setResizable(false);
            tablahabitaciones.getColumnModel().getColumn(2).setResizable(false);
            tablahabitaciones.getColumnModel().getColumn(3).setResizable(false);
            tablahabitaciones.getColumnModel().getColumn(4).setResizable(false);
            tablahabitaciones.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 895, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 129, 930, 470));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Asignar Habitacion ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 930, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablahabitaciones;
    // End of variables declaration//GEN-END:variables
}
